# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9dbda4d278cc5e30b455edf28f481b2c03ed09d080a9853dd12d8fcb3ff25e8d508fa006335bfaafd810f64479424855d02fd6f8b90330b25f63e4c2c427825a

test:
  secret_key_base: a2e971e18fbb83912522ff4b5dbbcb972adc999b5f4bdf2ec300518e55b54e03c3197333a476c34f79db34743457386f424f3c0d1d636a2793874d1c30067151

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
